---
- hosts: all 
  tasks:
   - name: "Install dependencies"
     apt:
             state: present
             pkg:
                - automake
                - bison
                - cmake
                - doxygen
                - flex
                - git
                - libc-ares-dev
                - libcmocka-dev
                - libjson-c-dev
                - libpcre3-dev
                - libpython-dev
                - libreadline-dev
                - libsystemd-dev
                - libtool
                - python-pip
                - python-pytest
                - python3-dev
                - python3-sphinx
                - sphinx-common
                - texinfo
                - valgrind
                - libyang0.16
                - libyang-dev
                - libcap-dev
  
   - name: "Add frr group"
     group:
             name: frr
             system: yes
             gid: 92
             state: present

   - name: "Add frrvty group"
     group:
             name: frrvty
             system: yes
             gid: 85
             state: present

   - name: "Add frr user"
     user:
             name: frr
             system: yes
             group: frr
             home: /var/opt/frr/ 
             comment: "FFR suite"
             shell: "/bin/false"
 
   - name: "Add groups to frr user"
     user: 
                name: frr
                append: yes
                groups: frrvty,frr

   - name: "Download Frr"
     git:
             repo: http://github.com/frrouting/frr.git
             dest: /home/pi/frr
   
   - name: "Prepare for configure"
     command: ./bootstrap.sh
     args:
             chdir: /home/pi/frr

   - name: "Configure Settings"
     command: "./configure --enable-exampledir=/usr/share/doc/frr/examples/ --localstatedir=/var/opt/frr --sbindir=/usr/lib/frr --sysconfdir=/etc/frr --enable-multipath=64 --enable-user=frr --enable-group=frr --enable-vty-group=frrvty --enable-configfile-mask=0640 -enable-logfile-mask=0640 --enable-fpm --with-pkg-git-version --with-pkg-extra-version=NiaB_FRR_Version"
     args:
             chdir: /home/pi/frr

   - name: "Make"
     command: make
     args:
             chdir: /home/pi/frr

   - name: "Make install"
     command: make install
     args:
             chdir: /home/pi/frr

   - name: "Make directories"
     command: "{{item}}"
     with_items:
             - "install -m 755 -o frr -g frr -d /var/log/frr"
             - "install -m 755 -o frr -g frr -d /var/opt/frr"
             - "install -m 755 -o frr -g frrvty -d /etc/frr"
             - "install -m 640 -o frr -g frr /dev/null /etc/frr/zebra.conf"
             - "install -m 640 -o frr -g frr /dev/null /etc/frr/bgpd.conf"
             - "install -m 640 -o frr -g frr /dev/null /etc/frr/ospfd.conf"
             - "install -m 640 -o frr -g frr /dev/null /etc/frr/ospf6d.conf"
             - "install -m 640 -o frr -g frr /dev/null /etc/frr/isisd.conf"
             - "install -m 640 -o frr -g frr /dev/null /etc/frr/ripd.conf"
             - "install -m 640 -o frr -g frr /dev/null /etc/frr/ripngd.conf"
             - "install -m 640 -o frr -g frr /dev/null /etc/frr/pimd.conf"
             - "install -m 640 -o frr -g frr /dev/null /etc/frr/ldpd.conf"
             - "install -m 640 -o frr -g frr /dev/null /etc/frr/nhrpd.conf"
             - "install -m 640 -o frr -g frrvty /dev/null /etc/frr/vtysh.conf"

   - name: "Enable IPv4 fowarding"
     command: "find /etc/sysctl.conf -type f -exec sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' {} \\;"

   - name: "Echo into vtysh.conf"
     command: bash -c "echo service integrated-vtysh-config > /etc/frr/vtysh.conf"

   - name: "Create daemons file"
     file:
             path: /etc/frr/daemons
             state: touch
   
   - name: "Configure frr daemons"
     blockinfile:
             path: /etc/frr/daemons
             marker: ""
             block: |
                     zebra=yes
                     bgpd=no
                     ospfd=yes
                     ospf6d=no
                     ripd=no
                     ripngd=no
                     isisd=no
                     pimd=no
                     ldpd=no
                     nhrpd=no
                     eigrpd=no
                     babeld=no
                     sharpd=no
                     staticd=yes
                     pbrd=no
                     bfdd=no
                     fabricd=no

   - name: "Create daemons.conf file"
     file:
             path: /etc/frr/daemons.conf
             state: touch
   
   - name: "Configure frr daemons.conf"
     blockinfile:
             path: /etc/frr/daemons.conf
             marker: ""
             block: |
                     vtysh_enable=yes
                     zebra_options=" -s 90000000 --daemon -A 127.0.0.1"
                     bgpd_options=" --daemon -A 127.0.0.1"
                     ospfd_options=" --daemon -A  127.0.0.1"
                     ospf6d_options=" --daemon -A 127.0.0.1"
                     ripd_options=" --daemon -A 127.0.0.1"
                     ripngd_options=" --daemon -A 127.0.0.1"
                     isisd_options=" --daemon -A 127.0.0.1"
                     pimd_options=" --daemon -A 127.0.0.1"
                     ldpd_options=" --daemon -A 127.0.0.1"
                     nhrpd_options=" --daemon -A 127.0.0.1"
                     eigrpd_options=" --daemon -A 127.0.0.1"   
                     babeld_options=" --daemon -A 127.0.0.1"
                     sharpd_options=" --daemon -A 127.0.0.1"
                     staticd_options=" --daemon -A 127.0.0.1"
                     pbrd_options=" --daemon -A 127.0.0.1"
                     bfdd_options=" --daemon -A 127.0.0.1"
                     fabricd_options=" --daemon -A 127.0.0.1"  

   - name: "Echo into ld.so.conf and run ldconfig"
     command: bash -c "echo include /usr/local/lib >> /etc/ld.so.conf && ldconfig"

   - name: "Copy over frr configuration template"
     copy:
             src: /home/isaac/Ansible/frr.conf
             dest: /etc/frr/frr.conf
             owner: frr
             group: frr
             mode: '0777'

- hosts: 192.168.137.10 
  tasks:

   - name: "Change loopback address in frr configuration template"
     replace:
             path: /etc/frr/frr.conf
             regexp: 'loopback_addr'
             replace: '10.10.10.0'

- hosts: 192.168.137.20 
  tasks:

   - name: "Change loopback address in frr configuration template"
     replace:
             path: /etc/frr/frr.conf
             regexp: 'loopback_addr'
             replace: '20.20.20.0'

- hosts: 192.168.137.30 
  tasks:

   - name: "Change loopback address in frr configuration template"
     replace:
             path: /etc/frr/frr.conf
             regexp: 'loopback_addr'
             replace: '30.30.30.0'

- hosts: 192.168.137.40 
  tasks:

  - name: "Change loopback address in frr configuration template"
    replace:
           path: /etc/frr/frr.conf
           regexp: 'loopback_addr'
           replace: '40.40.40.0'

- hosts: all
  tasks:

  - name: "Start FRRouting"
    command: /usr/lib/frr/frr start
